corrected yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -12,26 +12,26 @@ jobs:
 
     steps:
       - name: Checkout code
-      - uses: actions/checkout@v4
+        uses: actions/checkout@v4
 
-      - name: Validate file strucutre
+      - name: Validate file structure
         run: |
           echo "Checking for index.html..."
-          test -f index.html || (echo "Error: No index html file found" && exit 1)
+          test -f index.html || (echo "Error: No index.html file found" && exit 1)
 
           echo "Checking for styles folder..."
-          test -d css | test -d styles || (echo "Error: No folder for CSS files found" && exit 1")
+          test -d css || test -d styles || (echo "Error: No folder for CSS files found" && exit 1)
 
-      - name: Set up Node.js
-        uses: actions/setup-node@v2
-        with:
-          node-version: "20.19.1"
+      # - name: Set up Node.js
+      #   uses: actions/setup-node@v4
+      #   with:
+      #     node-version: "20.19.1"
 
-      - name: Install dependencies
-        run: npm install
+      # - name: Install dependencies
+      #   run: npm install
 
-      - name: Run tests
-        run: npm test
+      # - name: Run tests
+      #   run: npm test
 
-      - name: Run lint
-        run: npm run lint
+      # - name: Run lint
+      #   run: npm run lint
